#!/usr/bin/env node
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

/**
 * Bundle the in-iframe harness runtime (src/harness/harness-entry.ts, which
 * imports the patcher + morphdom) into a single self-contained IIFE at
 * harness/harness.js. This is a STATIC ASSET generation step, not part of the
 * package's typecheck/lint/test build — the committed harness.js is what the
 * app serves over pd-preview://. Re-run after changing the harness runtime:
 *
 *   pnpm --filter @pi-desktop/canvas build:harness
 */
const pkgDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

await build({
  entryPoints: [path.join(pkgDir, 'src/harness/harness-entry.ts')],
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: ['es2020'],
  minify: true,
  legalComments: 'none',
  banner: {
    js: '/* @pi-desktop/canvas harness — generated by scripts/build-harness.mjs. Do not edit. */',
  },
  outfile: path.join(pkgDir, 'harness/harness.js'),
});

console.log('built harness/harness.js');
