/**
 * Bobble 3D studio store — the workspace's UI + pipeline state in one zustand
 * store. Assets are LIVE state: ONLY what was generated by the real engine or
 * imported/dropped by the user this session — there is no bundled placeholder
 * model, no fixture assets, no credits, no promo state. Selectors used by
 * components stay primitive (single fields) to avoid selector thrash.
 */
import { create } from 'zustand';
import { TRIPO_ANIMS } from './data';

/** Left-rail tools — one per functional pipeline section (flat: no sub-tools). */
export type TripoTool = 'image' | 'model' | 'segment' | 'retopo' | 'texture' | 'animate';

export type TripoRightTab = 'assets' | 'history' | 'property';
/** Input for geometry generation: one-or-more unlabeled images (TRELLIS-2 does
 * arbitrary multi-image conditioning — more images improve accuracy), or text. */
export type TripoInputMode = 'image' | 'text';

/** A picked input image: the absolute disk path the engine reads, a display
 * name, and an in-renderer object URL for the thumbnail preview (the raw path
 * usually sits outside the sandbox, so pd-file:// can't show it). */
export interface PickedImage {
  readonly path: string;
  readonly name: string;
  readonly url: string;
}
/** Viewport render modes; wireframe is a separate ON/OFF overlay toggle that
 * draws edges ON TOP of the active mode (jedd). */
export type TripoRenderMode = 'clay' | 'textured' | 'normal';
export type TripoModal = null | 'help' | 'export';

/**
 * The pipeline stage the viewer is currently showing for the loaded asset:
 *   mesh    → the dense generated/imported base mesh (solid).
 *   segment → the mesh split into colored semantic parts (CubePart stage).
 *   retopo  → the clean quad-topology remesh (quad wireframe revealed).
 *   texture → the mesh with a generated texture applied (Textured mode).
 *   rig     → the mesh with its skeleton/bones overlaid (bind pose).
 *   animate → the rigged mesh playing a skeletal animation clip.
 * Every stage runs on a REAL model — one the engine generated or the user
 * imported. The per-stage engines are named in data.ts; where an engine isn't
 * installed the stage prompts its download rather than faking a result.
 */
export type TripoStage = 'mesh' | 'segment' | 'retopo' | 'texture' | 'rig' | 'animate';

/** Which operation produced a version. 'source' is the imported/generated root. */
export type TripoOp = 'source' | 'segment' | 'retopo' | 'texture' | 'rig';

/**
 * One node on an asset's history tree.
 *
 * Every pipeline op used to mint a whole new top-level asset, so a single model
 * put through segment → retopo → texture → rig littered the grid with five
 * unrelated cards. A version is a NODE instead: it records which version it was
 * derived from, so the history is a tree and re-running an op on an earlier
 * state creates a BRANCH rather than overwriting anything.
 *
 * `id` is also the asset-registry key for this version's bytes, and `thumb` is
 * a REAL viewer-captured preview — never icon artwork.
 */
export interface AssetVersion {
  readonly id: string;
  /** The version this one was derived from; null for the root. */
  readonly parentId: string | null;
  readonly op: TripoOp;
  /** Short human label, e.g. "Retopology · 3,086 quads". */
  readonly label: string;
  readonly created: number;
  readonly thumb: string | null;
  readonly faces: number;
  readonly vertices: number;
  /** Real topology of this version, e.g. "Quad" — written by the viewer. */
  readonly topology: string | null;
  /** True once this version carries a skeleton + skin weights. */
  readonly rigged?: boolean;
  /** Whether the rigged shape actually measured as humanoid — the animation
   * presets are humanoid clips and stay hidden when it did not. */
  readonly humanoid?: boolean;
  /** On-disk path — what the gen3d engine's stage ops take as input. */
  readonly diskPath?: string;
}

/** One asset in the right-panel grid: a name plus its whole history tree. The
 * card always shows `currentVersionId` — the working version. */
export interface StudioAsset {
  readonly id: string;
  readonly name: string;
  readonly source: 'generated' | 'imported';
  readonly created: string;
  /** Which version IS the asset right now (what the grid + viewer show). */
  readonly currentVersionId: string;
  readonly versions: readonly AssetVersion[];
}

/** The version an asset currently resolves to (never undefined in practice —
 * an asset always has at least its root). */
export function currentVersion(asset: StudioAsset): AssetVersion | undefined {
  return asset.versions.find((v) => v.id === asset.currentVersionId) ?? asset.versions[0];
}

export function findVersion(
  assets: readonly StudioAsset[],
  versionId: string,
): { asset: StudioAsset; version: AssetVersion } | null {
  for (const asset of assets) {
    const version = asset.versions.find((v) => v.id === versionId);
    if (version !== undefined) return { asset, version };
  }
  return null;
}

/** Root-to-leaf depth of a version, for drawing the tree. */
export function versionDepth(asset: StudioAsset, version: AssetVersion): number {
  let depth = 0;
  let parent = version.parentId;
  while (parent !== null) {
    const next = asset.versions.find((v) => v.id === parent);
    if (next === undefined) break;
    depth += 1;
    parent = next.parentId;
  }
  return depth;
}

/** True when this version has more than one child — i.e. the tree branches. */
export function hasSiblings(asset: StudioAsset, version: AssetVersion): boolean {
  return asset.versions.filter((v) => v.parentId === version.parentId).length > 1;
}

/** A row in the (real) task-history popover: stages run this session. */
export interface StageHistoryRow {
  readonly id: string;
  readonly label: string;
  readonly sub: string;
}

/* ── ARDY: motions + the animation state machine (for motion matching) ───────
 * A motion clip is a named animation — a bundled preset (previews on the dummy)
 * or one authored from a natural-language description via ARDY. The state
 * machine wires motions into a graph the runtime blends between: states are
 * motions, transitions carry a parameter condition. Exported, this graph IS a
 * motion-matching set a game can drive. */
export interface MotionClip {
  readonly id: string;
  readonly name: string;
  readonly kind: 'preset' | 'generated';
  /** NL description that authored a generated motion. */
  readonly prompt?: string;
  /** Which bundled preview to show for this clip (a TRIPO_ANIMS id). */
  readonly previewId?: string;
}
/** A driving parameter (Speed, MoveX, Grounded…). bool stores 0|1. */
export interface BlendParam {
  readonly id: string;
  readonly name: string;
  readonly type: 'float' | 'bool';
  readonly value: number;
}
/** A state in the machine = a motion placed on the graph canvas. */
export interface BlendState {
  readonly id: string;
  readonly motionId: string;
  readonly x: number;
  readonly y: number;
}
/** A transition edge with a single parameter condition. */
export interface BlendTransition {
  readonly id: string;
  readonly from: string;
  readonly to: string;
  readonly paramId: string;
  readonly op: '>' | '<' | '==' | '!=';
  readonly value: number;
}

const STAGE_LABEL: Record<TripoStage, string> = {
  mesh: 'Generate Model',
  segment: 'Segment Parts',
  retopo: 'Retopology',
  texture: 'Generate Texture',
  rig: 'Rig & Skeleton',
  animate: 'Animate',
};

interface TripoState {
  // ── layout / navigation
  tool: TripoTool;
  rightTab: TripoRightTab;
  /** The single open popover/dropdown (all menus are mutually exclusive). */
  openMenu: string | null;
  modal: TripoModal;

  // ── generate-model panel
  inputMode: TripoInputMode;
  prompt: string;
  geoTexOpen: boolean;
  faceLimit: number;
  topology: 'triangle' | 'quad';
  symmetry: 'auto' | 'on' | 'off';
  genModel: string;
  /** TRELLIS structure resolution preset for generation. */
  genResolution: 'low' | 'medium' | 'high';
  /** Which shape model text→3D uses. TRELLIS goes via an image; Cube3D does
   * not, and produces no texture. Image→3D is always TRELLIS. */
  genEngine: 'trellis2' | 'cube3d';
  /**
   * Every image this session produced, oldest first: a generation followed by
   * whatever edits were made from it. The user picks which one becomes 3D, so
   * an edit must not throw away what it started from.
   */
  imageVersions: readonly { readonly path: string; readonly label: string }[];
  /** Index into imageVersions the panel is showing / will act on. */
  imageIndex: number;
  /** Draw the rig's bones over the model. Only meaningful when hasSkeleton. */
  showSkeleton: boolean;
  /** The loaded model actually carries a skin — set by the viewer on load, so
   * the toggle appears only where there is something to show. */
  hasSkeleton: boolean;
  /** TRELLIS bake resolution in texels. */
  genTextureSize: 1024 | 2048 | 4096;
  /** Cube3D: comma-separated part names to split the result into (optional). */
  genParts: string;
  /** Chain Hunyuan Paint texturing after geometry. */
  genAutoTexture: boolean;
  /** Picked input images for image→3D (1 = single image, more = multi-image
   * conditioning; unlabeled, TRELLIS pools them — more improve accuracy). */
  genImages: readonly PickedImage[];

  // ── animate panel
  skeleton: boolean;
  animFilter: 'all' | 'basic' | 'interactive';
  animSearch: string;
  selectedAnim: string;
  /** NL action prompt for generating a motion with ARDY. */
  motionPrompt: string;
  /** Every motion available to place in the state machine. */
  motionLibrary: readonly MotionClip[];
  /** The animation state machine (motion matching). */
  blendParams: readonly BlendParam[];
  blendStates: readonly BlendState[];
  blendTransitions: readonly BlendTransition[];
  entryStateId: string | null;
  selectedStateId: string | null;
  selectedTransitionId: string | null;
  /** State id we're drawing a transition FROM (null = not connecting). */
  connectFromId: string | null;
  /** Show the full-viewport state-machine editor. */
  graphOpen: boolean;

  // ── viewer
  loadedAssetId: string | null;
  /** Which pipeline result the viewer renders for the loaded asset. */
  pipelineStage: TripoStage;
  renderMode: TripoRenderMode;
  /** Edge overlay drawn on top of the active render mode. */
  wireframe: boolean;
  showGrid: boolean;
  autoRotate: boolean;
  envLight: boolean;
  lightIntensity: number;
  meshVisible: boolean;
  /** Real topology counts of what is on screen — written by the viewer. */
  stats: { topology: string; faces: number; vertices: number } | null;
  /** Part names from the segment stage — written by the viewer. */
  segmentParts: readonly string[];

  // ── assets panel (live state, no fixtures)
  assets: readonly StudioAsset[];
  selectedAssetId: string | null;
  assetFilter: 'all' | 'generated' | 'imported';
  manageMode: boolean;
  checkedAssets: readonly string[];
  /** A history node the user is INSPECTING without making it current; null =
   * show the asset's working version. */
  previewVersionId: string | null;
  /** The history tree panel is open. */
  historyOpen: boolean;
  /** Rig gating: the "is this humanoid?" question, raised by the shape probe. */
  humanoidPrompt: {
    readonly assetId: string;
    readonly isHumanoid: boolean;
    readonly confidence: number;
    readonly reasons: readonly string[];
  } | null;

  // ── history (real: stages run this session)
  history: readonly StageHistoryRow[];

  // ── property panel (hierarchy)
  hierarchyCollapsed: readonly string[];
  hiddenNodes: readonly string[];
  selectedNode: string | null;

  // ── actions
  setTool: (tool: TripoTool) => void;
  set: <K extends keyof TripoState>(key: K, value: TripoState[K]) => void;
  toggleMenu: (id: string) => void;
  closeMenus: () => void;
  loadAsset: (id: string) => void;
  /** Advance the loaded asset to a pipeline stage (no-op if nothing loaded). */
  runStage: (stage: TripoStage) => void;
  /** A brand-new asset (import or fresh generation) with its root version. */
  addAsset: (asset: StudioAsset) => void;
  /** An op produced a new state OF AN EXISTING asset: append a tree node under
   * `parentVersionId` and make it the working version. */
  addVersion: (assetId: string, parentVersionId: string, version: AssetVersion) => void;
  /** Make an existing version the asset's working version (switch branch). */
  setCurrentVersion: (assetId: string, versionId: string) => void;
  /** Inspect a version without making it current (null = back to current). */
  previewVersion: (versionId: string | null) => void;
  /** The viewer captured a real rendered preview for a version. */
  setAssetThumb: (versionId: string, thumb: string) => void;
  setAssetCounts: (
    versionId: string,
    faces: number,
    vertices: number,
    topology?: string,
  ) => void;
  /** The version the viewer should render right now. */
  activeVersionId: () => string | null;
  toggleList: (key: 'checkedAssets' | 'hierarchyCollapsed' | 'hiddenNodes', id: string) => void;
  removeChecked: () => void;

  // ── motions + state machine
  /** Author a motion from the NL prompt (ARDY) and add it to the library. */
  generateMotion: () => void;
  /** Place a motion on the graph as a new state (first one = entry). */
  addBlendState: (motionId: string) => void;
  moveBlendState: (id: string, x: number, y: number) => void;
  removeBlendState: (id: string) => void;
  setEntryState: (id: string) => void;
  /** Begin/finish drawing a transition between two states. */
  beginConnect: (id: string) => void;
  finishConnect: (toId: string) => void;
  cancelConnect: () => void;
  updateTransition: (id: string, patch: Partial<Omit<BlendTransition, 'id'>>) => void;
  removeTransition: (id: string) => void;
  addBlendParam: () => void;
  updateBlendParam: (id: string, patch: Partial<Omit<BlendParam, 'id'>>) => void;
  removeBlendParam: (id: string) => void;
}

const toggled = (list: readonly string[], id: string): readonly string[] =>
  list.includes(id) ? list.filter((x) => x !== id) : [...list, id];

/** Monotonic id source for session-created entities (states, params, motions). */
let seq = 0;
const nextId = (prefix: string): string => `${prefix}-${++seq}`;

/**
 * Preset ids are asset filenames ("angry_01", "sad_01", "dance_01"). They were
 * being used verbatim as the card labels, so raw snake_case filenames were the
 * only place in the app where storage naming leaked into the UI. The id stays
 * the id (testids and previewId still key off it); only the label is humanized.
 */
const motionLabel = (id: string): string => {
  const words = id.replace(/_0*(\d+)$/, ' $1').replace(/_/g, ' ');
  return words.charAt(0).toUpperCase() + words.slice(1);
};

/** The starter motion library — every bundled preset, previewing on the dummy. */
const SEED_MOTIONS: readonly MotionClip[] = TRIPO_ANIMS.map((a) => ({
  id: `m-${a.id}`,
  name: motionLabel(a.id),
  kind: 'preset',
  previewId: a.id,
}));

/** The parameters most locomotion state machines drive. */
const SEED_PARAMS: readonly BlendParam[] = [
  { id: 'p-speed', name: 'Speed', type: 'float', value: 0 },
  { id: 'p-movex', name: 'MoveX', type: 'float', value: 0 },
  { id: 'p-grounded', name: 'Grounded', type: 'bool', value: 1 },
];

export const useTripoStore = create<TripoState>((set, get) => ({
  tool: 'model',
  rightTab: 'assets',
  openMenu: null,
  modal: null,

  inputMode: 'image',
  prompt: '',
  geoTexOpen: false,
  faceLimit: 30,
  topology: 'triangle',
  symmetry: 'auto',
  genModel: 'trellis-2',
  genResolution: 'medium',
  genEngine: 'trellis2',
  imageVersions: [],
  imageIndex: 0,
  showSkeleton: false,
  hasSkeleton: false,
  genTextureSize: 2048,
  genParts: '',
  genAutoTexture: true,
  genImages: [],

  skeleton: false,
  animFilter: 'all',
  animSearch: '',
  selectedAnim: 'angry_01',
  motionPrompt: '',
  motionLibrary: SEED_MOTIONS,
  blendParams: SEED_PARAMS,
  blendStates: [],
  blendTransitions: [],
  entryStateId: null,
  selectedStateId: null,
  selectedTransitionId: null,
  connectFromId: null,
  graphOpen: false,

  loadedAssetId: null,
  pipelineStage: 'mesh',
  renderMode: 'clay',
  wireframe: false,
  showGrid: false,
  autoRotate: false,
  envLight: true,
  lightIntensity: 60,
  meshVisible: true,
  stats: null,
  segmentParts: [],

  assets: [],
  selectedAssetId: null,
  assetFilter: 'all',
  manageMode: false,
  checkedAssets: [],
  previewVersionId: null,
  historyOpen: false,
  humanoidPrompt: null,

  history: [],

  hierarchyCollapsed: [],
  hiddenNodes: [],
  selectedNode: 'mesh-node',

  setTool: (tool) => set({ tool, openMenu: null }),
  set: (key, value) => set({ [key]: value } as Partial<TripoState>),
  toggleMenu: (id) => set((s) => ({ openMenu: s.openMenu === id ? null : id })),
  closeMenus: () => set({ openMenu: null }),
  loadAsset: (id) => {
    if (!get().assets.some((a) => a.id === id)) return;
    set({
      loadedAssetId: id,
      selectedAssetId: id,
      previewVersionId: null,
      meshVisible: true,
      // A freshly loaded asset starts at its base mesh in Clay.
      pipelineStage: 'mesh',
      renderMode: 'clay',
      segmentParts: [],
      // NO auto-help. The "View Your Model" navigation dialog is strictly
      // user-initiated — it used to open itself the first time a model landed
      // in the viewport, which meant it fired on ordinary clicks and had to be
      // dismissed before you could touch the model. It now opens ONLY from the
      // "?" button in the viewport rail (jedd).
    });
  },
  runStage: (stage) =>
    set((s) => {
      // Every stage runs on a real loaded asset — nothing to advance otherwise.
      if (s.loadedAssetId === null) return {};
      const asset = s.assets.find((a) => a.id === s.loadedAssetId);
      if (asset === undefined) return {};
      return {
        pipelineStage: stage,
        selectedAssetId: s.selectedAssetId ?? s.loadedAssetId,
        meshVisible: true,
        // The texture stage is what the Textured mode exists to show.
        renderMode: stage === 'texture' ? 'textured' : s.renderMode,
        segmentParts: stage === 'segment' ? s.segmentParts : [],
        history: [
          { id: `h-${s.history.length + 1}`, label: STAGE_LABEL[stage], sub: asset.name },
          ...s.history,
        ].slice(0, 12),
      };
    }),
  addAsset: (asset) =>
    set((s) => ({
      assets: [asset, ...s.assets],
    })),
  addVersion: (assetId, parentVersionId, version) =>
    set((s) => ({
      assets: s.assets.map((a) =>
        a.id === assetId
          ? {
              ...a,
              versions: [...a.versions, { ...version, parentId: parentVersionId }],
              // A freshly produced state IS the new working version; the old one
              // stays on the tree and stays switchable.
              currentVersionId: version.id,
            }
          : a,
      ),
      // Inspecting an older node then running an op should land you on the
      // result, not leave you stranded in the past.
      previewVersionId: null,
      selectedAssetId: assetId,
      loadedAssetId: assetId,
    })),
  setCurrentVersion: (assetId, versionId) =>
    set((s) => ({
      assets: s.assets.map((a) =>
        a.id === assetId && a.versions.some((v) => v.id === versionId)
          ? { ...a, currentVersionId: versionId }
          : a,
      ),
      previewVersionId: null,
    })),
  previewVersion: (versionId) => set({ previewVersionId: versionId }),
  setAssetThumb: (versionId, thumb) =>
    set((s) => ({
      assets: s.assets.map((a) =>
        a.versions.some((v) => v.id === versionId)
          ? { ...a, versions: a.versions.map((v) => (v.id === versionId ? { ...v, thumb } : v)) }
          : a,
      ),
    })),
  setAssetCounts: (versionId, faces, vertices, topology) =>
    set((s) => ({
      assets: s.assets.map((a) =>
        a.versions.some((v) => v.id === versionId)
          ? {
              ...a,
              versions: a.versions.map((v) =>
                v.id === versionId
                  ? { ...v, faces, vertices, topology: topology ?? v.topology }
                  : v,
              ),
            }
          : a,
      ),
    })),
  activeVersionId: () => {
    const s = get();
    if (s.previewVersionId !== null) return s.previewVersionId;
    const asset = s.assets.find((a) => a.id === s.loadedAssetId);
    return asset === undefined ? null : asset.currentVersionId;
  },
  toggleList: (key, id) => set((s) => ({ [key]: toggled(s[key], id) }) as Partial<TripoState>),
  removeChecked: () =>
    set((s) => ({
      assets: s.assets.filter((a) => !s.checkedAssets.includes(a.id)),
      checkedAssets: [],
      manageMode: false,
      loadedAssetId: s.checkedAssets.includes(s.loadedAssetId ?? '') ? null : s.loadedAssetId,
      selectedAssetId: s.checkedAssets.includes(s.selectedAssetId ?? '') ? null : s.selectedAssetId,
    })),

  // ── motions + state machine ─────────────────────────────────────────────
  generateMotion: () =>
    set((s) => {
      const prompt = s.motionPrompt.trim();
      if (prompt.length === 0) return {};
      const name = prompt.length <= 26 ? prompt : `${prompt.slice(0, 24).replace(/\s+\S*$/, '')}…`;
      // Reuse a bundled preview whose name the description mentions, so the new
      // motion has a plausible thumbnail until a live ARDY clip is rendered.
      const lower = prompt.toLowerCase();
      const hit = SEED_MOTIONS.find((m) => {
        const stem = m.name.split('_')[0] ?? m.name;
        return stem.length > 2 && lower.includes(stem);
      });
      const motion: MotionClip = {
        id: nextId('m'),
        name,
        kind: 'generated',
        prompt,
        ...(hit?.previewId !== undefined ? { previewId: hit.previewId } : {}),
      };
      return { motionLibrary: [motion, ...s.motionLibrary], motionPrompt: '' };
    }),
  addBlendState: (motionId) =>
    set((s) => {
      const id = nextId('st');
      // Spread new nodes across the canvas with room for edges + labels.
      const n = s.blendStates.length;
      const x = 48 + (n % 3) * 210;
      const y = 56 + Math.floor(n / 3) * 150;
      return {
        blendStates: [...s.blendStates, { id, motionId, x, y }],
        entryStateId: s.entryStateId ?? id,
        selectedStateId: id,
        selectedTransitionId: null,
      };
    }),
  moveBlendState: (id, x, y) =>
    set((s) => ({
      blendStates: s.blendStates.map((st) => (st.id === id ? { ...st, x, y } : st)),
    })),
  removeBlendState: (id) =>
    set((s) => {
      const states = s.blendStates.filter((st) => st.id !== id);
      return {
        blendStates: states,
        blendTransitions: s.blendTransitions.filter((t) => t.from !== id && t.to !== id),
        entryStateId: s.entryStateId === id ? (states[0]?.id ?? null) : s.entryStateId,
        selectedStateId: s.selectedStateId === id ? null : s.selectedStateId,
        connectFromId: s.connectFromId === id ? null : s.connectFromId,
      };
    }),
  setEntryState: (id) => set({ entryStateId: id }),
  beginConnect: (id) => set({ connectFromId: id }),
  cancelConnect: () => set({ connectFromId: null }),
  finishConnect: (toId) =>
    set((s) => {
      const from = s.connectFromId;
      if (from === null || from === toId) return { connectFromId: null };
      // No duplicate edge for the same ordered pair.
      if (s.blendTransitions.some((t) => t.from === from && t.to === toId)) {
        return { connectFromId: null };
      }
      const param = s.blendParams[0];
      const t: BlendTransition = {
        id: nextId('tr'),
        from,
        to: toId,
        paramId: param?.id ?? 'p-speed',
        op: param?.type === 'bool' ? '==' : '>',
        value: param?.type === 'bool' ? 1 : 0.5,
      };
      return {
        blendTransitions: [...s.blendTransitions, t],
        connectFromId: null,
        selectedTransitionId: t.id,
        selectedStateId: null,
      };
    }),
  updateTransition: (id, patch) =>
    set((s) => ({
      blendTransitions: s.blendTransitions.map((t) => (t.id === id ? { ...t, ...patch } : t)),
    })),
  removeTransition: (id) =>
    set((s) => ({
      blendTransitions: s.blendTransitions.filter((t) => t.id !== id),
      selectedTransitionId: s.selectedTransitionId === id ? null : s.selectedTransitionId,
    })),
  addBlendParam: () =>
    set((s) => ({
      blendParams: [
        ...s.blendParams,
        { id: nextId('p'), name: `Param${s.blendParams.length + 1}`, type: 'float', value: 0 },
      ],
    })),
  updateBlendParam: (id, patch) =>
    set((s) => ({
      blendParams: s.blendParams.map((p) => (p.id === id ? { ...p, ...patch } : p)),
    })),
  removeBlendParam: (id) =>
    set((s) => ({
      blendParams: s.blendParams.filter((p) => p.id !== id),
      // Drop transitions that referenced the removed parameter.
      blendTransitions: s.blendTransitions.filter((t) => t.paramId !== id),
    })),
}));
