/**
 * Bobble 3D studio store — the workspace's UI + pipeline state in one zustand
 * store. Assets are LIVE state: ONLY what was generated by the real engine or
 * imported/dropped by the user this session — there is no bundled placeholder
 * model, no fixture assets, no credits, no promo state. Selectors used by
 * components stay primitive (single fields) to avoid selector thrash.
 */
import { create } from 'zustand';
import { TRIPO_ANIMS } from './data';

/** Left-rail tools — one per functional pipeline section (flat: no sub-tools). */
export type TripoTool = 'image' | 'model' | 'segment' | 'retopo' | 'texture' | 'animate';

export type TripoRightTab = 'assets' | 'property';
/** Input for geometry generation: one-or-more unlabeled images (TRELLIS-2 does
 * arbitrary multi-image conditioning — more images improve accuracy), or text. */
export type TripoInputMode = 'image' | 'text';

/** A picked input image: the absolute disk path the engine reads, a display
 * name, and an in-renderer object URL for the thumbnail preview (the raw path
 * usually sits outside the sandbox, so pd-file:// can't show it). */
export interface PickedImage {
  readonly path: string;
  readonly name: string;
  readonly url: string;
}
/** Viewport render modes; wireframe is a separate ON/OFF overlay toggle that
 * draws edges ON TOP of the active mode (jedd). */
export type TripoRenderMode = 'clay' | 'textured' | 'normal';
export type TripoModal = null | 'help' | 'export';

/**
 * The pipeline stage the viewer is currently showing for the loaded asset:
 *   mesh    → the dense generated/imported base mesh (solid).
 *   segment → the mesh split into colored semantic parts (CubePart stage).
 *   retopo  → the clean quad-topology remesh (quad wireframe revealed).
 *   texture → the mesh with a generated texture applied (Textured mode).
 *   rig     → the mesh with its skeleton/bones overlaid (bind pose).
 *   animate → the rigged mesh playing a skeletal animation clip.
 * Every stage runs on a REAL model — one the engine generated or the user
 * imported. The per-stage engines are named in data.ts; where an engine isn't
 * installed the stage prompts its download rather than faking a result.
 */
export type TripoStage = 'mesh' | 'segment' | 'retopo' | 'texture' | 'rig' | 'animate';

/** One asset in the right-panel grid. `thumb` is a REAL rendered preview (a
 * viewer-captured dataURL) — never icon artwork. */
export interface StudioAsset {
  readonly id: string;
  readonly name: string;
  readonly source: 'generated' | 'imported';
  readonly rigged?: boolean;
  readonly thumb: string | null;
  /** On-disk path — what the gen3d engine's stage ops take as input. Every
   * asset has one (imported file path or engine artifact path). */
  readonly diskPath?: string;
  readonly faces: number;
  readonly vertices: number;
  readonly created: string;
}

/** A row in the (real) task-history popover: stages run this session. */
export interface StageHistoryRow {
  readonly id: string;
  readonly label: string;
  readonly sub: string;
}

/* ── ARDY: motions + the animation state machine (for motion matching) ───────
 * A motion clip is a named animation — a bundled preset (previews on the dummy)
 * or one authored from a natural-language description via ARDY. The state
 * machine wires motions into a graph the runtime blends between: states are
 * motions, transitions carry a parameter condition. Exported, this graph IS a
 * motion-matching set a game can drive. */
export interface MotionClip {
  readonly id: string;
  readonly name: string;
  readonly kind: 'preset' | 'generated';
  /** NL description that authored a generated motion. */
  readonly prompt?: string;
  /** Which bundled preview to show for this clip (a TRIPO_ANIMS id). */
  readonly previewId?: string;
}
/** A driving parameter (Speed, MoveX, Grounded…). bool stores 0|1. */
export interface BlendParam {
  readonly id: string;
  readonly name: string;
  readonly type: 'float' | 'bool';
  readonly value: number;
}
/** A state in the machine = a motion placed on the graph canvas. */
export interface BlendState {
  readonly id: string;
  readonly motionId: string;
  readonly x: number;
  readonly y: number;
}
/** A transition edge with a single parameter condition. */
export interface BlendTransition {
  readonly id: string;
  readonly from: string;
  readonly to: string;
  readonly paramId: string;
  readonly op: '>' | '<' | '==' | '!=';
  readonly value: number;
}

const STAGE_LABEL: Record<TripoStage, string> = {
  mesh: 'Generate Model',
  segment: 'Segment Parts',
  retopo: 'Retopology',
  texture: 'Generate Texture',
  rig: 'Rig & Skeleton',
  animate: 'Animate',
};

interface TripoState {
  // ── layout / navigation
  tool: TripoTool;
  rightTab: TripoRightTab;
  /** The single open popover/dropdown (all menus are mutually exclusive). */
  openMenu: string | null;
  modal: TripoModal;
  helpSeen: boolean;

  // ── generate-model panel
  inputMode: TripoInputMode;
  prompt: string;
  geoTexOpen: boolean;
  faceLimit: number;
  topology: 'triangle' | 'quad';
  symmetry: 'auto' | 'on' | 'off';
  genModel: string;
  /** TRELLIS structure resolution preset for generation. */
  genResolution: 'low' | 'medium' | 'high';
  /** Chain Hunyuan Paint texturing after geometry. */
  genAutoTexture: boolean;
  /** Picked input images for image→3D (1 = single image, more = multi-image
   * conditioning; unlabeled, TRELLIS pools them — more improve accuracy). */
  genImages: readonly PickedImage[];

  // ── animate panel
  skeleton: boolean;
  animFilter: 'all' | 'basic' | 'interactive';
  animSearch: string;
  selectedAnim: string;
  /** NL action prompt for generating a motion with ARDY. */
  motionPrompt: string;
  /** Every motion available to place in the state machine. */
  motionLibrary: readonly MotionClip[];
  /** The animation state machine (motion matching). */
  blendParams: readonly BlendParam[];
  blendStates: readonly BlendState[];
  blendTransitions: readonly BlendTransition[];
  entryStateId: string | null;
  selectedStateId: string | null;
  selectedTransitionId: string | null;
  /** State id we're drawing a transition FROM (null = not connecting). */
  connectFromId: string | null;
  /** Show the full-viewport state-machine editor. */
  graphOpen: boolean;

  // ── viewer
  loadedAssetId: string | null;
  /** Which pipeline result the viewer renders for the loaded asset. */
  pipelineStage: TripoStage;
  renderMode: TripoRenderMode;
  /** Edge overlay drawn on top of the active render mode. */
  wireframe: boolean;
  showGrid: boolean;
  autoRotate: boolean;
  envLight: boolean;
  lightIntensity: number;
  meshVisible: boolean;
  /** Real topology counts of what is on screen — written by the viewer. */
  stats: { topology: string; faces: number; vertices: number } | null;
  /** Part names from the segment stage — written by the viewer. */
  segmentParts: readonly string[];

  // ── assets panel (live state, no fixtures)
  assets: readonly StudioAsset[];
  selectedAssetId: string | null;
  assetFilter: 'all' | 'generated' | 'imported';
  manageMode: boolean;
  checkedAssets: readonly string[];

  // ── history (real: stages run this session)
  history: readonly StageHistoryRow[];

  // ── property panel (hierarchy)
  hierarchyCollapsed: readonly string[];
  hiddenNodes: readonly string[];
  selectedNode: string | null;

  // ── actions
  setTool: (tool: TripoTool) => void;
  set: <K extends keyof TripoState>(key: K, value: TripoState[K]) => void;
  toggleMenu: (id: string) => void;
  closeMenus: () => void;
  loadAsset: (id: string) => void;
  /** Advance the loaded asset to a pipeline stage (no-op if nothing loaded). */
  runStage: (stage: TripoStage) => void;
  addAsset: (asset: StudioAsset) => void;
  /** The viewer captured a real rendered preview for an asset. */
  setAssetThumb: (id: string, thumb: string) => void;
  setAssetCounts: (id: string, faces: number, vertices: number) => void;
  toggleList: (key: 'checkedAssets' | 'hierarchyCollapsed' | 'hiddenNodes', id: string) => void;
  removeChecked: () => void;

  // ── motions + state machine
  /** Author a motion from the NL prompt (ARDY) and add it to the library. */
  generateMotion: () => void;
  /** Place a motion on the graph as a new state (first one = entry). */
  addBlendState: (motionId: string) => void;
  moveBlendState: (id: string, x: number, y: number) => void;
  removeBlendState: (id: string) => void;
  setEntryState: (id: string) => void;
  /** Begin/finish drawing a transition between two states. */
  beginConnect: (id: string) => void;
  finishConnect: (toId: string) => void;
  cancelConnect: () => void;
  updateTransition: (id: string, patch: Partial<Omit<BlendTransition, 'id'>>) => void;
  removeTransition: (id: string) => void;
  addBlendParam: () => void;
  updateBlendParam: (id: string, patch: Partial<Omit<BlendParam, 'id'>>) => void;
  removeBlendParam: (id: string) => void;
}

const toggled = (list: readonly string[], id: string): readonly string[] =>
  list.includes(id) ? list.filter((x) => x !== id) : [...list, id];

/** Monotonic id source for session-created entities (states, params, motions). */
let seq = 0;
const nextId = (prefix: string): string => `${prefix}-${++seq}`;

/** The starter motion library — every bundled preset, previewing on the dummy. */
const SEED_MOTIONS: readonly MotionClip[] = TRIPO_ANIMS.map((a) => ({
  id: `m-${a.id}`,
  name: a.id,
  kind: 'preset',
  previewId: a.id,
}));

/** The parameters most locomotion state machines drive. */
const SEED_PARAMS: readonly BlendParam[] = [
  { id: 'p-speed', name: 'Speed', type: 'float', value: 0 },
  { id: 'p-movex', name: 'MoveX', type: 'float', value: 0 },
  { id: 'p-grounded', name: 'Grounded', type: 'bool', value: 1 },
];

export const useTripoStore = create<TripoState>((set, get) => ({
  tool: 'model',
  rightTab: 'assets',
  openMenu: null,
  modal: null,
  helpSeen: false,

  inputMode: 'image',
  prompt: '',
  geoTexOpen: false,
  faceLimit: 30,
  topology: 'triangle',
  symmetry: 'auto',
  genModel: 'trellis-2',
  genResolution: 'medium',
  genAutoTexture: true,
  genImages: [],

  skeleton: false,
  animFilter: 'all',
  animSearch: '',
  selectedAnim: 'angry_01',
  motionPrompt: '',
  motionLibrary: SEED_MOTIONS,
  blendParams: SEED_PARAMS,
  blendStates: [],
  blendTransitions: [],
  entryStateId: null,
  selectedStateId: null,
  selectedTransitionId: null,
  connectFromId: null,
  graphOpen: false,

  loadedAssetId: null,
  pipelineStage: 'mesh',
  renderMode: 'clay',
  wireframe: false,
  showGrid: false,
  autoRotate: false,
  envLight: true,
  lightIntensity: 60,
  meshVisible: true,
  stats: null,
  segmentParts: [],

  assets: [],
  selectedAssetId: null,
  assetFilter: 'all',
  manageMode: false,
  checkedAssets: [],

  history: [],

  hierarchyCollapsed: [],
  hiddenNodes: [],
  selectedNode: 'mesh-node',

  setTool: (tool) => set({ tool, openMenu: null }),
  set: (key, value) => set({ [key]: value } as Partial<TripoState>),
  toggleMenu: (id) => set((s) => ({ openMenu: s.openMenu === id ? null : id })),
  closeMenus: () => set({ openMenu: null }),
  loadAsset: (id) => {
    const first = !get().helpSeen;
    if (!get().assets.some((a) => a.id === id)) return;
    set({
      loadedAssetId: id,
      selectedAssetId: id,
      meshVisible: true,
      // A freshly loaded asset starts at its base mesh in Clay.
      pipelineStage: 'mesh',
      renderMode: 'clay',
      segmentParts: [],
      // The "View Your Model" coach dialog appears the first time a model
      // lands in the viewport, then never again.
      modal: first ? 'help' : get().modal,
      helpSeen: true,
    });
  },
  runStage: (stage) =>
    set((s) => {
      // Every stage runs on a real loaded asset — nothing to advance otherwise.
      if (s.loadedAssetId === null) return {};
      const asset = s.assets.find((a) => a.id === s.loadedAssetId);
      if (asset === undefined) return {};
      return {
        pipelineStage: stage,
        selectedAssetId: s.selectedAssetId ?? s.loadedAssetId,
        meshVisible: true,
        // The texture stage is what the Textured mode exists to show.
        renderMode: stage === 'texture' ? 'textured' : s.renderMode,
        segmentParts: stage === 'segment' ? s.segmentParts : [],
        history: [
          { id: `h-${s.history.length + 1}`, label: STAGE_LABEL[stage], sub: asset.name },
          ...s.history,
        ].slice(0, 12),
      };
    }),
  addAsset: (asset) =>
    set((s) => ({
      assets: [asset, ...s.assets],
    })),
  setAssetThumb: (id, thumb) =>
    set((s) => ({
      assets: s.assets.map((a) => (a.id === id ? { ...a, thumb } : a)),
    })),
  setAssetCounts: (id, faces, vertices) =>
    set((s) => ({
      assets: s.assets.map((a) => (a.id === id ? { ...a, faces, vertices } : a)),
    })),
  toggleList: (key, id) => set((s) => ({ [key]: toggled(s[key], id) }) as Partial<TripoState>),
  removeChecked: () =>
    set((s) => ({
      assets: s.assets.filter((a) => !s.checkedAssets.includes(a.id)),
      checkedAssets: [],
      manageMode: false,
      loadedAssetId: s.checkedAssets.includes(s.loadedAssetId ?? '') ? null : s.loadedAssetId,
      selectedAssetId: s.checkedAssets.includes(s.selectedAssetId ?? '') ? null : s.selectedAssetId,
    })),

  // ── motions + state machine ─────────────────────────────────────────────
  generateMotion: () =>
    set((s) => {
      const prompt = s.motionPrompt.trim();
      if (prompt.length === 0) return {};
      const name = prompt.length <= 26 ? prompt : `${prompt.slice(0, 24).replace(/\s+\S*$/, '')}…`;
      // Reuse a bundled preview whose name the description mentions, so the new
      // motion has a plausible thumbnail until a live ARDY clip is rendered.
      const lower = prompt.toLowerCase();
      const hit = SEED_MOTIONS.find((m) => {
        const stem = m.name.split('_')[0] ?? m.name;
        return stem.length > 2 && lower.includes(stem);
      });
      const motion: MotionClip = {
        id: nextId('m'),
        name,
        kind: 'generated',
        prompt,
        ...(hit?.previewId !== undefined ? { previewId: hit.previewId } : {}),
      };
      return { motionLibrary: [motion, ...s.motionLibrary], motionPrompt: '' };
    }),
  addBlendState: (motionId) =>
    set((s) => {
      const id = nextId('st');
      // Spread new nodes across the canvas with room for edges + labels.
      const n = s.blendStates.length;
      const x = 48 + (n % 3) * 210;
      const y = 56 + Math.floor(n / 3) * 150;
      return {
        blendStates: [...s.blendStates, { id, motionId, x, y }],
        entryStateId: s.entryStateId ?? id,
        selectedStateId: id,
        selectedTransitionId: null,
      };
    }),
  moveBlendState: (id, x, y) =>
    set((s) => ({
      blendStates: s.blendStates.map((st) => (st.id === id ? { ...st, x, y } : st)),
    })),
  removeBlendState: (id) =>
    set((s) => {
      const states = s.blendStates.filter((st) => st.id !== id);
      return {
        blendStates: states,
        blendTransitions: s.blendTransitions.filter((t) => t.from !== id && t.to !== id),
        entryStateId: s.entryStateId === id ? (states[0]?.id ?? null) : s.entryStateId,
        selectedStateId: s.selectedStateId === id ? null : s.selectedStateId,
        connectFromId: s.connectFromId === id ? null : s.connectFromId,
      };
    }),
  setEntryState: (id) => set({ entryStateId: id }),
  beginConnect: (id) => set({ connectFromId: id }),
  cancelConnect: () => set({ connectFromId: null }),
  finishConnect: (toId) =>
    set((s) => {
      const from = s.connectFromId;
      if (from === null || from === toId) return { connectFromId: null };
      // No duplicate edge for the same ordered pair.
      if (s.blendTransitions.some((t) => t.from === from && t.to === toId)) {
        return { connectFromId: null };
      }
      const param = s.blendParams[0];
      const t: BlendTransition = {
        id: nextId('tr'),
        from,
        to: toId,
        paramId: param?.id ?? 'p-speed',
        op: param?.type === 'bool' ? '==' : '>',
        value: param?.type === 'bool' ? 1 : 0.5,
      };
      return {
        blendTransitions: [...s.blendTransitions, t],
        connectFromId: null,
        selectedTransitionId: t.id,
        selectedStateId: null,
      };
    }),
  updateTransition: (id, patch) =>
    set((s) => ({
      blendTransitions: s.blendTransitions.map((t) => (t.id === id ? { ...t, ...patch } : t)),
    })),
  removeTransition: (id) =>
    set((s) => ({
      blendTransitions: s.blendTransitions.filter((t) => t.id !== id),
      selectedTransitionId: s.selectedTransitionId === id ? null : s.selectedTransitionId,
    })),
  addBlendParam: () =>
    set((s) => ({
      blendParams: [
        ...s.blendParams,
        { id: nextId('p'), name: `Param${s.blendParams.length + 1}`, type: 'float', value: 0 },
      ],
    })),
  updateBlendParam: (id, patch) =>
    set((s) => ({
      blendParams: s.blendParams.map((p) => (p.id === id ? { ...p, ...patch } : p)),
    })),
  removeBlendParam: (id) =>
    set((s) => ({
      blendParams: s.blendParams.filter((p) => p.id !== id),
      // Drop transitions that referenced the removed parameter.
      blendTransitions: s.blendTransitions.filter((t) => t.paramId !== id),
    })),
}));
